# Test various architectures by building out binaries with cibuildwheel.
name: test-wheels

on:
  # Trigger the workflow on master but also allow it to run manually.
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test-emulated:
    name: "cibuildwheel: ${{ matrix.platform.build }}"
    permissions:
      contents: read
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - build: "cp315-manylinux_aarch64"
            os: ubuntu-24.04-arm
          - build: "cp314-manylinux_s390x"
            os: ubuntu-latest
            emulation: true
          - build: "cp39-manylinux_x86_64"
            os: ubuntu-latest
          - build: "cp314t-musllinux_x86_64"
            os: ubuntu-latest
          - build: "cp313-macosx_arm64"
            os: macos-15
          - build: "cp313-win_amd64"
            os: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 2
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
        if: ${{ matrix.platform.emulation }}
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@294735312765b09d24a2fbec22660ce817587d55 # v4.1.0
        env:
          # NOTE(vytas): Uncomment to test against alpha/beta CPython
          #   (usually May-July until rc1).
          CIBW_ENABLE: cpython-prerelease

          CIBW_ARCHS_LINUX: all
          CIBW_BUILD: ${{ matrix.platform.build }}
