# Other tests, primarily those requiring obsolete dependencies.
name: test-other

on:
  push:
    branches:
      - "*"
  # TODO(vytas): Remove from the default run once verified in a PR.
  pull_request:
    branches:
      - master

jobs:
  run-tox:
    name: tox -e ${{ matrix.tox.env }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox:
          - env: "py310_smoke"
            python-version: "3.10"
          - env: "py310_smoke_cython"
            python-version: "3.10"
          - env: "wsgi_meinheld"
            python-version: "3.9"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.tox.python-version }}

      - name: Install smoke test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libunwind-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools tox wheel
          python --version
          pip --version
          tox --version

      - name: Run tox
        run: tox -e ${{ matrix.tox.env }}
