name: Run tests (CPython 3.5.2)

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  run_tox:
    name: tox -e py35 (3.5.2 on ubuntu-16.04)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Run tox
        uses: docker://ubuntu:16.04
        env:
          DEBIAN_FRONTEND: noninteractive
        with:
          # NOTE(vytas): We upgrade pip in the venv in two steps, because 8.1.1
          #   does not properly resolve python_requires.
          args: |
            /bin/bash -c "
            apt-get update &&
            apt-get install -y build-essential python3.5 python3.5-dev python3-venv &&
            python3.5 -m venv venv &&
            source venv/bin/activate &&
            pip install -U 'pip < 20' &&
            pip install -U pip setuptools tox wheel &&
            python --version &&
            pip --version &&
            tox --version &&
            tox -e py35"
